name: CI
on:
  push:
    branches: [main]

jobs:
  lint-and-unit:
    runs-on: ubuntu-latest
    container: bats/bats:1.11.0
    steps:
      - uses: actions/checkout@v4
      - name: "Test"
        run: "task"
