name: CI
on:
  push:
    branches: [main]

jobs:
  lint-and-unit:
    runs-on: ubuntu-latest
    container:
      image: donaldm314/ubuntu-bats:28
      options: --user root
    steps:
      - uses: actions/checkout@v4
      - name: "Test"
        run: |
          task
          id
          ls -lart
