name: CI
on:
  push:
    branches: [main]

jobs:
  checkout-and-test:
    runs-on: ubuntu-latest
    container:
      image: donaldm314/ubuntu-bats:28
      options: --user ubuntu
    steps:
      - uses: actions/checkout@v4
      - name: "Test"
        run: task
